### ISSUE TITLE
Add DoNotOverwriteSidebar option in the Publish_GitHub_Wiki_Content task

### ISSUE THREAD

**Issue by ykuijs** [dsccommunity/DscResource.DocGenerator#105]
#### Details of the scenario you tried and the problem that is occurring

The current code of the Publish_GitHub_Wiki_Content task always generates a new Wiki sidebar markdown file: https://github.com/dsccommunity/DscResource.DocGenerator/blob/main/source/Private/New-WikiSidebar.ps1#L54-L61

For my repo I am using a custom side bar and don't want it to be overwritten. Please add a possibility to specify that you don't want the sidebar to be overwritten, so I can start using the task to automatically update the wiki content.

#### Steps to reproduce the problem

Publish a new version in a repo that uses this task, it will always overwrite the sidebar

#### Expected behavior

Specify a parameter to prevent the creation of a new sidebar.

#### Current behavior

Will always overwrite the sidebar

#### Suggested solution to the issue

Add a parameter somewhere to specify you don't want the sidebar to be generated.

#### The operating system the target node is running

N/A

#### Version and build of PowerShell the target node is running

N/A

#### Version of the module that was used

Most recent

**Comment by johlju** [comment]
I think we just make sure that if there is an existing sidebar file in the WikiContent folder when publishing, a new sidebar is not created nor overwritten. I see no point of having a option to toggle it. If you don't want a static (or manually updated sidebar) then you don't put one in WikiSource.

If you want to keep a manually update sidebar then you put the `_Sidebar.md` in the WikiSource folder.

Working on a fix.

**Comment by ykuijs** [comment]
But what if you release a new version, which generates a sidebar. Then with the next release, you want the sidebar to be updated, for example because new resources has been added for which documentation has been generated that should be added to the sidebar as well. But since the WikiSource already contains the previously generated sidebar, with your change this will never be updated after it was generated once.

I think the toggle would make more sense. Then the repo owner can specify if he wants the sidebar to be generated or not.

**Comment by johlju** [comment]
The sidebar is only created during publishing. What happens is (if I'm not totally mistaken):

During build
1. all wiki documentation is generated for the resources in WikiOutput
2. All files in WikiSource is copied to WikiOutput. 

During publish
1. The side bar is generated based on the content of WikiOutput, excluding files starting with _. Unless the sidebar already exist, then the step is skipped (with my change). 

So for repos that want the sidebar to be dynamically updated, those repos should _not_ add a file _Sidebar.md to WikiSource. •, like for SqlServerDsc. 

For repos that want to control the sidebar themself those repos (like SharePointDsc) should add the existing sidebar file to WikiSource.

**Comment by ykuijs** [comment]
Not sure I fully understand? What do you mean with WikiSource?

**Comment by johlju** [comment]
WikiSource is a folder under the source folder, it is meant to contain additional documentation that will be added to WikiOutput during build, and then published to the wiki during the deploy stage. 

See the folder in SqlServerDsc:
https://github.com/dsccommunity/SqlServerDsc/tree/main/source/WikiSource

**Comment by ykuijs** [comment]
Great, thanks for the explanation. In that case the change makes total sense 😄
