### ISSUE TITLE
Include subfolders/files in the WikiSource

### ISSUE THREAD

**Issue by ykuijs** [dsccommunity/DscResource.DocGenerator#109]
#### Details of the scenario you tried and the problem that is occurring

Currently the Generate_Wiki_Content task only copies the files in the WikiSource and is ignoring the files in subfolders. Please make this recursive.

#### Steps to reproduce the problem

Create a folder with some files in the WikiSource. These aren't copied to the WikiContent folder.

#### Expected behavior

All files are copied

#### Current behavior

Only files in the WikiSource folder itself are copied and subfolders are ignored.

#### Suggested solution to the issue

Add -Recurse to this line:
https://github.com/dsccommunity/DscResource.DocGenerator/blob/main/source/tasks/Generate_Wiki_Content.build.ps1#L166

#### Version of the module that was used
v0.10.2

**Comment by johlju** [comment]
This functionally is meant if there is a images folder that is being generated. Not for markdown files since they would not show up in the sidebar (as far as I know).
