### ISSUE TITLE
Cannot generate Wiki for inherited properties in class-based resource if class inherit more than once

### ISSUE THREAD

**Issue by johlju** [dsccommunity/DscResource.DocGenerator#116]
#### Details of the scenario you tried and the problem that is occurring
Cannot generate the properties for the wiki when inherits more than once. See [DnsRecordNsScoped](https://github.com/dsccommunity/DnsServerDsc/wiki/DnsRecordNsScoped), this one inherits from DnsRecordNs, which inherits from DnsRecordBase and then inherits from DnsBaseProperties. It only get the properties from DnsRecordNsScoped  and DnsRecordNs, but missing properties from DnsRecordBase and DnsBaseProperties.

#### Steps to reproduce the problem
Build the repo DnsServerDsc

#### Expected behavior
Should output all inherited properties.

#### Current behavior
Missing properties.

#### Suggested solution to the issue
Loop through all parent classes.

#### The operating system the target node is running
n/a

#### Version and build of PowerShell the target node is running
n/a

#### Version of the module that was used
0.10.3

**Comment by gaelcolas** [comment]
as per #126 if you "import" the class with `using module ModuleName`, you can do this:
```
[MyTest].GetProperties().Name 
```
Basically listing all properties.
