### ISSUE TITLE
DocGeneration fails on Ubuntu-2204 image with libmi error

### ISSUE THREAD

**Issue by PlagueHO** [dsccommunity/DscResource.DocGenerator#131]
#### Details of the scenario you tried and the problem that is occurring

Running the Doc Generation task on an `ubuntu-2204` (usually just `ubuntu-latest`) fails with:
```text
Generating conceptual help for all DSC resources based on source.
ERROR: Failed to import classes from file /home/vsts/work/1/s/source/DSCResources/DSC_Disk/DSC_Disk.schema.mof. Error Exception calling "ImportClasses" with "3" argument(s): "Unable to load shared library 'libmi' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibmi: cannot open shared object file: No such file or directory"
At /home/vsts/work/1/s/output/RequiredModules/DscResource.DocGenerator/0.11.2/DscResource.DocGenerator.psm1:1495 char:9
+         throw "Failed to import classes from file $FileName. Error $_ …
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At /home/vsts/work/1/s/output/RequiredModules/DscResource.DocGenerator/0.11.2/tasks/Generate_Conceptual_Help.build.ps1:81 char:1
+ task Generate_Conceptual_Help {
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Build FAILED. 9 tasks, 1 errors, 0 warnings 00:00:03.1080050
Exception: Failed to import classes from file
/home/vsts/work/1/s/source/DSCResources/DSC_Disk/DSC_Disk.schema.mof. Error
Exception calling "ImportClasses" with "3" argument(s): "Unable to load shared
library 'libmi' or one of its dependencies. In order to help diagnose loading
problems, consider setting the LD_DEBUG environment variable: liblibmi: cannot
open shared object file: No such file or directory"
```

#### Steps to reproduce the problem
Run the pipeline for any DSC resource using automated doc generation and using an `ubuntu-latest` image. See https://dev.azure.com/dsccommunity/StorageDsc/_build/results?buildId=7403&view=logs&jobId=bce26a94-9049-50eb-6c1c-385ccbec51f9&j=bce26a94-9049-50eb-6c1c-385ccbec51f9&t=512e4b73-7a3e-57af-0534-ae809c1351da

#### Expected behavior
Should perform the build.

#### Current behavior
Throws exception:
Exception: Failed to import classes from file
/home/vsts/work/1/s/source/DSCResources/DSC_Disk/DSC_Disk.schema.mof. Error
Exception calling "ImportClasses" with "3" argument(s): "Unable to load shared
library 'libmi' or one of its dependencies. In order to help diagnose loading
problems, consider setting the LD_DEBUG environment variable: liblibmi: cannot
open shared object file: No such file or directory"

#### Suggested solution to the issue
Temporary solution is to pin build image to `ubuntu-20.04`. Long term solution needs investigation.

#### The operating system the target node is running
`ubuntu-20.04`

#### Version of the module that was used
Latest

**Comment by nyanhp** [comment]
Maybe it would be worthwhile to build and pack MOF-based modules on Windows. Installing `libmi` (OMI) on any new Ubuntu version requires downgrading to some ancient openssl libs. The timeline with regards to more recent version of openssl does not look promising to be honest: <https://github.com/microsoft/omi/issues/715>
A downgrade to the required version of openssl is not advisable.

**Comment by nyanhp** [comment]
Right, I forgot about PSWSMan. I can confirm that the DocGenerator build task works on Ubuntu 22.04 WSL (and likely also 20) after using `Install-WSMAN`.

**Comment by nyanhp** [comment]
@gaelcolas the pipelines are still failing. Did your talks result in any new information, or should we try using PSWSMan?

**Comment by gaelcolas** [comment]
PSWSMan works :)
https://github.com/Azure/nxtools/blob/main/azure-pipelines.yml#L53

**Comment by PlagueHO** [comment]
I have now noticed that this issue has also started occurring with Ubuntu-20.04 (in StorageDsc) at least.

**Comment by johlju** [comment]
When I encounter this I move the pipeline to `windows-latest` instead.

**Comment by PlagueHO** [comment]
That is what I have done. Does solve it.

**Comment by johlju** [comment]
The tests in this repo are now skipped on Linux. There are to much work keeping DSC up to date on Linux and going forward stuff for Linux should be tested on DSCv3.
