### ISSUE TITLE
Make `Generate_Wiki_Content` a metatask that runs other build tasks

### ISSUE THREAD

**Issue by johlju** [dsccommunity/DscResource.DocGenerator#135]
Suggest making `Generate_Wiki_Content` a metatask and the current `Generate_Wiki_Content` is renamed to `Generate_Markdown_For_DSC_Resources` (or something similar). 

The new metatask `Generate_Wiki_Content` will run all the tasks that is needed to generate the wiki content:

- `Generate_Markdown_For_DSC_Resources`
- `Generate_Markdown_For_Public_Commands`
- `Generate_External_Help_File_For_Public_Commands`
- `Clean_Markdown_Of_Public_Commands`

**Comment by johlju** [comment]
There is an issue excluding certain part of the documentation being generated. To simplify that I suggest we should also have:

- New tasks `Create_Wiki_Output_Folder` for the code:

https://github.com/dsccommunity/DscResource.DocGenerator/blob/bb3932363f20bb1413e1094369f8ee8a8053f252/source/tasks/Generate_Wiki_Content.build.ps1#L88-L95

- New task `Copy_Source_Wiki_Folder` for the code:

https://github.com/dsccommunity/DscResource.DocGenerator/blob/bb3932363f20bb1413e1094369f8ee8a8053f252/source/tasks/Generate_Wiki_Content.build.ps1#L97-L104 

https://github.com/dsccommunity/DscResource.DocGenerator/blob/bb3932363f20bb1413e1094369f8ee8a8053f252/source/tasks/Generate_Wiki_Content.build.ps1#L112-L126

- The following code goes into the (above) suggested `Generate_Markdown_For_DSC_Resources`:

https://github.com/dsccommunity/DscResource.DocGenerator/blob/bb3932363f20bb1413e1094369f8ee8a8053f252/source/tasks/Generate_Wiki_Content.build.ps1#L106-L110

**Comment by dan-hughes** [comment]
@johlju, do you have an example of this. Looks to be a good one to release at the same time as the other task addition.

**Comment by johlju** [comment]
A meta task is made the same way as other task, it just references other tasks instead of having code by itself

```
Task Generate_Wiki_Content Create_Wiki_Output_Folder, Copy_Source_Wiki_Folder, Generate_Markdown_For_DSC_Resources, Generate_Markdown_For_Public_Commands, Generate_External_Help_File_For_Public_Commands, Clean_Markdown_Of_Public_Commands
```

Happy to review this if you have the time.

**Comment by dan-hughes** [comment]
Params - are these the same for each of the tasks?
Also how can I pass variables between tasks?

**Comment by johlju** [comment]
Yes I would say so, unless one is not specifically used I guess it can be skipped 🤔
But easiest is just copy all peaks to all tasks.
