### ISSUE TITLE
Conceptual help cannot be generated if the README.md is using upper-case

### ISSUE THREAD

**Issue by johlju** [dsccommunity/DscResource.DocGenerator#42]
When the conceptual help is generated on Linux the filenames are case sensitive so if a repository is using the word README in upper-case the conceptual help will not be generated. 

https://github.com/dsccommunity/DscResource.DocGenerator/blob/5d436656d1e469beaccd2d700b6e2ccfb9456d3d/source/Public/New-DscResourcePowerShellHelp.ps1#L100

**Comment by gaelcolas** [comment]
If you use Get-Item instead I think it's case insensitive.
Get-Item -Path ... -EA SilentlyContinue
