### ISSUE TITLE
New-DscResourcePowerShellHelp: Verbose message string should be added as a localized string

### ISSUE THREAD

**Issue by johlju** [dsccommunity/DscResource.DocGenerator#6]
Verbose message string should be added as a localized string.

https://github.com/dsccommunity/DscResource.DocGenerator/blob/6486a706623c2f7816609355f913d7ab93545ad0/source/Public/New-DscResourcePowerShellHelp.ps1#L110

**Comment by 96RadhikaJadhav** [comment]
@johlju  Did you mean here just to add "" to the message string?

**Comment by johlju** [comment]
Thanks for asking. I meant adding the message to the localized string file https://github.com/dsccommunity/DscResource.DocGenerator/blob/main/source/en-US/DscResource.DocGenerator.strings.psd1 than change the `Write-Verbose` to use the new localized string (see other Write-Verbose for an example).

**Comment by johlju** [comment]
This was fixed in a recent PR.
