### ISSUE TITLE
[Publish_GitHub_Wiki_Content] Write-Build if $GitHubToken not specified

### ISSUE THREAD

**Issue by phbits** [dsccommunity/DscResource.DocGenerator#75]
When working with this module locally, significant time was spent to figure out why this task kept being skipped. The documentation for this task clearly states:

> The task will only run if the variable $GitHubToken is set either in parent scope, as an environment variable, or if passed to the build task.
> [Source](https://github.com/dsccommunity/DscResource.DocGenerator#publish_github_wiki_content)

However wouldn't it be more useful to output that status?

The current `Publish_GitHub_Wiki_Content.build.ps1` is as follows:

```powershell
task Publish_GitHub_Wiki_Content -if ($GitHubToken) {
...
}
```

What I'm proposing is something along the lines of:

```powershell
task Publish_GitHub_Wiki_Content {

    if ($GitHubToken)
    {
        # do same stuff

    } else {

        Write-Build SomeColor '$GitHubToken not set via parent scope, as an environment variable, or passed to the build task.'
        Write-Build SomeColor 'Skipping task: Publish_GitHub_Wiki_Content'
}
```

**Comment by johlju** [comment]
By using `-if ($GitHubToken)` the command `Invoke-Build` evaluates if the task should be run and never actually starts the task, saving execution time. I would rather have seen that `Invoke-Build` supports an optional `-SkipMessage` instead. 🤔  
But I can see the value in this so I can review a PR that adds this.
